### PR TITLE
refactor(logger): Add logger

### PR DESCRIPTION
**Pull request by rluvaton**
Add logger so we'll abstract that layer (in case we wanna change to
winston for example)

### CODE REVIEW

**Comment by rluvaton** [comment]
> Good job on this! Can you resolve the merge conflict too, please?

Thanks, I’ll do it in the morning 😀

**Comment by rluvaton** [comment]
> Just noticed an issue. If we plan to use this logger abstraction for both the firebase functions and the Next app, you'll want to use the commonJS module export style — as opposed to ES6. The firebase side is not using ES6.
Will Do 👍 

> Also, when resolving the merge conflicts, just remove any existing console.log statements. You don't need to replace them with logger.
Every log statement? even on errors?

**Comment by Miikis** [comment]
You can leave the error logs. They're not really placed strategically at the moment — just kinda ad hoc. If you were to remove them, it wouldn't be a big deal. At least until we get a proper logger in there.

**Comment by rluvaton** [comment]
@Miikis fix #23 too (because it didn't let me commit)

**Pull request merged**
